        ara_api_wsgi_server: gunicorn
        ara_api_wsgi_bind: 0.0.0.0 # "{{ ara_api_fqdn }}"
        ara_api_allowed_hosts:
            - '*'
            - "127.0.0.1"
            - "localhost"
            - "::1"
            # - "{{ ara_api_fqdn }}"
        ara_api_database_engine: django.db.backends.postgresql
        ara_api_database_name: jawad
        ara_api_database_user: postgres
        ara_api_database_password: admin123
        ara_api_database_host: database-2.c7z3d7fsjdte.ap-southeast-2.rds.amazonaws.com
        ara_api_database_port: 5432
       # ARA_LOGGING - Python logging configuration
        ara_api_logging:
          version: 1
          disable_existing_loggers: false
          formatters:
            normal:
              format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
            handlers:
              console:
                class: logging.handlers.TimedRotatingFileHandler
                formatter: normal
                level: "{{ ara_api_log_level }}"
                filename: "{{ ara_api_log_dir }}/server.log"
                when: 'midnight'
                interval: 1
                backupCount: 30
            loggers:
              ara:
                handlers:
                  - console
                level: "{{ ara_api_log_level }}"
                propagate: 0
              postgres:
                handlers:
                  - console
                level: INFO